title: Cargese Spin Glass 2018
author: krzakala
email: florent.krzakala@ens.fr
description: Minimal backup website for cargese
baseurl: ""
url: "http://cargese.krzakala.org/"
github_username:  krzakala

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: Florent Krzakala @ ENS
gems:
  - jekyll-feed
  - jekyll-paginate
  
  
theme: jekyll-theme-slate
